"""Initial schema

Revision ID: 58bd5856b181
Revises: 
Create Date: 2026-08-07 15:04:31.244361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bd5856b181'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=17), nullable=False),
    sa.Column('nrc', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_nit'), ['nit'], unique=True)

    op.create_table('pla_concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('tipo_concepto', sa.Enum('INGRESO', 'DESCUENTO', 'APORTE_PATRONAL', 'PROVISION', name='tipoconceptoenum'), nullable=False),
    sa.Column('afecta_isss', sa.Boolean(), nullable=True),
    sa.Column('afecta_afp', sa.Boolean(), nullable=True),
    sa.Column('afecta_renta', sa.Boolean(), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('pla_concepto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_concepto_id'), ['id'], unique=False)

    op.create_table('pla_parametro_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fecha_vigencia', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    with op.batch_alter_table('pla_parametro_global', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_parametro_global_id'), ['id'], unique=False)

    op.create_table('pla_tramo_renta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_pago', sa.Enum('QUINCENAL', 'MENSUAL', name='periodorentaenum'), nullable=False),
    sa.Column('tramo_numero', sa.Integer(), nullable=False),
    sa.Column('desde_monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hasta_monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('porcentaje_aplicar', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('sobre_exceso_de', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cuota_fija', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pla_tramo_renta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_tramo_renta_id'), ['id'], unique=False)

    op.create_table('rh_catalogo_habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rh_catalogo_habilidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rh_catalogo_habilidad_id'), ['id'], unique=False)

    op.create_table('rh_catalogo_idioma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rh_catalogo_idioma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rh_catalogo_idioma_id'), ['id'], unique=False)

    op.create_table('seg_permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_permiso', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_permiso')
    )
    with op.batch_alter_table('seg_permiso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seg_permiso_id'), ['id'], unique=False)

    op.create_table('seg_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_rol')
    )
    with op.batch_alter_table('seg_rol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seg_rol_id'), ['id'], unique=False)

    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('estado_familiar', sa.String(length=20), nullable=False),
    sa.Column('profesion_oficio', sa.String(length=100), nullable=False),
    sa.Column('nacionalidad', sa.String(length=50), nullable=False),
    sa.Column('dui', sa.String(length=10), nullable=False),
    sa.Column('nit', sa.String(length=17), nullable=False),
    sa.Column('isss_afiliacion', sa.String(length=9), nullable=True),
    sa.Column('nup_afp', sa.String(length=12), nullable=True),
    sa.Column('puesto_id', sa.Integer(), nullable=True),
    sa.Column('departamento_residencia', sa.String(length=50), nullable=False),
    sa.Column('municipio_residencia', sa.String(length=50), nullable=False),
    sa.Column('distrito_residencia', sa.String(length=50), nullable=False),
    sa.Column('dui_departamento_expedicion', sa.String(length=50), nullable=False),
    sa.Column('dui_municipio_expedicion', sa.String(length=50), nullable=False),
    sa.Column('dui_distrito_expedicion', sa.String(length=50), nullable=False),
    sa.Column('dui_fecha_expedicion', sa.Date(), nullable=False),
    sa.Column('email_institucional', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empleados_dui'), ['dui'], unique=True)
        batch_op.create_index(batch_op.f('ix_empleados_email_institucional'), ['email_institucional'], unique=True)
        batch_op.create_index(batch_op.f('ix_empleados_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empleados_nit'), ['nit'], unique=True)

    op.create_table('org_estructura_organizativa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_unidad', sa.String(), nullable=False),
    sa.Column('tipo_unidad', sa.Enum('DIRECCION', 'GERENCIA', 'DEPARTAMENTO', 'SECCION', 'UNIDAD', 'AREA', name='tipounidadenum'), nullable=False),
    sa.Column('unidad_padre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['unidad_padre_id'], ['org_estructura_organizativa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_estructura_organizativa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_estructura_organizativa_id'), ['id'], unique=False)

    op.create_table('org_nivel_organizacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_nivel', sa.String(), nullable=False),
    sa.Column('peso_jerarquico', sa.Integer(), nullable=False),
    sa.Column('es_staff', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_nivel_organizacional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_nivel_organizacional_id'), ['id'], unique=False)

    op.create_table('pla_periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_periodo', sa.String(), nullable=False),
    sa.Column('tipo_planilla', sa.Enum('QUINCENAL', 'MENSUAL', 'AGUINALDO', 'VACACIONES', name='tipoplanillaenum'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTA', 'EN_PROCESO', 'CERRADA', 'PAGADA', name='estadoplanillaenum'), nullable=True),
    sa.Column('fecha_procesamiento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_periodo')
    )
    with op.batch_alter_table('pla_periodo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_periodo_id'), ['id'], unique=False)

    op.create_table('seg_rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['seg_permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['seg_rol.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('salario_base', sa.Float(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('proporciona_alojamiento', sa.Boolean(), nullable=False),
    sa.Column('direccion_alojamiento', sa.Text(), nullable=True),
    sa.Column('dias_jornada', sa.String(length=100), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('pausa_alimenticia_inicio', sa.Time(), nullable=False),
    sa.Column('pausa_alimenticia_fin', sa.Time(), nullable=False),
    sa.Column('horas_semanales', sa.Integer(), nullable=False),
    sa.Column('medio_pago', sa.String(length=50), nullable=False),
    sa.Column('lugar_pago', sa.Text(), nullable=False),
    sa.Column('herramientas_entregadas', sa.Text(), nullable=True),
    sa.Column('lugar_entrega_herramientas', sa.String(length=100), nullable=True),
    sa.Column('lugar_trabajo_direccion', sa.Text(), nullable=False),
    sa.Column('lugar_trabajo_distrito', sa.String(length=50), nullable=False),
    sa.Column('lugar_trabajo_municipio', sa.String(length=50), nullable=False),
    sa.Column('lugar_trabajo_departamento', sa.String(length=50), nullable=False),
    sa.Column('distrito_celebracion', sa.String(length=50), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_id'), ['id'], unique=False)

    op.create_table('dependientes_economicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('porcentaje_beneficio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dependientes_economicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependientes_economicos_id'), ['id'], unique=False)

    op.create_table('estudios_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('institucion', sa.String(length=150), nullable=False),
    sa.Column('titulo_obtenido', sa.String(length=150), nullable=False),
    sa.Column('fecha_graduacion', sa.Date(), nullable=True),
    sa.Column('nivel_estudio', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estudios_academicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estudios_academicos_id'), ['id'], unique=False)

    op.create_table('experiencias_laborales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=150), nullable=False),
    sa.Column('puesto_desempeniado', sa.String(length=150), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('motivo_salida', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiencias_laborales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiencias_laborales_id'), ['id'], unique=False)

    op.create_table('org_puesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_puesto', sa.String(), nullable=False),
    sa.Column('estructura_organizativa_id', sa.Integer(), nullable=False),
    sa.Column('nivel_organizacional_id', sa.Integer(), nullable=False),
    sa.Column('puesto_jefe_id', sa.Integer(), nullable=True),
    sa.Column('es_jefatura', sa.Boolean(), nullable=True),
    sa.Column('salario_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salario_maximo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('proposito_principal', sa.Text(), nullable=True),
    sa.Column('anios_experiencia_minima', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estructura_organizativa_id'], ['org_estructura_organizativa.id'], ),
    sa.ForeignKeyConstraint(['nivel_organizacional_id'], ['org_nivel_organizacional.id'], ),
    sa.ForeignKeyConstraint(['puesto_jefe_id'], ['org_puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_puesto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_puesto_id'), ['id'], unique=False)

    op.create_table('pla_beneficio_recurrente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('monto_asignado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['pla_concepto.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pla_beneficio_recurrente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_beneficio_recurrente_id'), ['id'], unique=False)

    op.create_table('pla_boleta_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('periodo_planilla_id', sa.Integer(), nullable=False),
    sa.Column('salario_base_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dias_trabajados', sa.Integer(), nullable=False),
    sa.Column('total_ingresos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_descuentos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('liquido_a_recibir', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['periodo_planilla_id'], ['pla_periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pla_boleta_pago', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_boleta_pago_id'), ['id'], unique=False)

    op.create_table('pla_novedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('periodo_planilla_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['concepto_id'], ['pla_concepto.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['periodo_planilla_id'], ['pla_periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pla_novedad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_novedad_id'), ['id'], unique=False)

    op.create_table('pla_prestamo_empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_prestamo', sa.Enum('INTERNO', 'BANCARIO', 'EMBARGO_JUDICIAL', 'ANTICIPO', name='tipoprestamoenum'), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cuota_periodica', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'PAGADO', 'SUSPENDIDO', name='estadoprestamoenum'), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pla_prestamo_empleado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_prestamo_empleado_id'), ['id'], unique=False)

    op.create_table('pla_registro_comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('periodo_planilla_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('monto_generado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('origen_calculo', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['pla_concepto.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['periodo_planilla_id'], ['pla_periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pla_registro_comision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_registro_comision_id'), ['id'], unique=False)

    op.create_table('rh_liquidacion_empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_retiro', sa.Date(), nullable=False),
    sa.Column('motivo_salida', sa.Enum('DESPIDO_INJUSTIFICADO', 'DESPIDO_JUSTIFICADO', 'RENUNCIA_VOLUNTARIA', 'MUTUO_ACUERDO', 'JUBILACION', 'DEFUNCION', name='motivosalidaenum'), nullable=False),
    sa.Column('salario_base_calculo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dias_laborados_pendientes', sa.Integer(), nullable=True),
    sa.Column('monto_salario_pendiente', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_vacacion_proporcional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_aguinaldo_proporcional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_indemnizacion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_ingresos_liquidacion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deducciones_ley', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_liquido_pagar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'APROBADA', 'PAGADA', name='estadoliquidacionenum'), nullable=True),
    sa.Column('documento_finiquito_url', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rh_liquidacion_empleado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rh_liquidacion_empleado_id'), ['id'], unique=False)

    op.create_table('seg_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['seg_rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('seg_usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seg_usuario_id'), ['id'], unique=False)

    op.create_table('org_asignacion_puesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('salario_asignado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo_asignacion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['puesto_id'], ['org_puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_asignacion_puesto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_asignacion_puesto_id'), ['id'], unique=False)

    op.create_table('org_requisito_academico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('nivel_estudio_minimo', sa.Enum('BASICA', 'BACHILLERATO', 'TECNICO', 'PREGRADO', 'POSTGRADO', 'DOCTORADO', 'CERTIFICACION', name='nivelestudioenum'), nullable=False),
    sa.Column('area_estudio', sa.String(), nullable=False),
    sa.Column('condicion_aceptable', sa.Enum('GRADUADO', 'EGRESADO', 'EN_CURSO', 'INCOMPLETO', name='estadoestudioenum'), nullable=False),
    sa.ForeignKeyConstraint(['puesto_id'], ['org_puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_requisito_academico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_requisito_academico_id'), ['id'], unique=False)

    op.create_table('org_requisito_habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('habilidad_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje_minimo_requerido', sa.Integer(), nullable=False),
    sa.Column('es_excluyente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['habilidad_id'], ['rh_catalogo_habilidad.id'], ),
    sa.ForeignKeyConstraint(['puesto_id'], ['org_puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_requisito_habilidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_requisito_habilidad_id'), ['id'], unique=False)

    op.create_table('org_requisito_idioma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('idioma_id', sa.Integer(), nullable=False),
    sa.Column('nivel_conversacion_minimo', sa.Integer(), nullable=True),
    sa.Column('nivel_lectura_minimo', sa.Integer(), nullable=True),
    sa.Column('nivel_escritura_minimo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idioma_id'], ['rh_catalogo_idioma.id'], ),
    sa.ForeignKeyConstraint(['puesto_id'], ['org_puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_requisito_idioma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_requisito_idioma_id'), ['id'], unique=False)

    op.create_table('org_responsabilidad_puesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_responsabilidad', sa.Text(), nullable=False),
    sa.Column('frecuencia', sa.Enum('DIARIA', 'SEMANAL', 'MENSUAL', 'OCASIONAL', name='frecuenciaenum'), nullable=False),
    sa.ForeignKeyConstraint(['puesto_id'], ['org_puesto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_responsabilidad_puesto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_responsabilidad_puesto_id'), ['id'], unique=False)

    op.create_table('pla_amortizacion_prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prestamo_empleado_id', sa.Integer(), nullable=False),
    sa.Column('boleta_pago_id', sa.Integer(), nullable=False),
    sa.Column('monto_amortizado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['boleta_pago_id'], ['pla_boleta_pago.id'], ),
    sa.ForeignKeyConstraint(['prestamo_empleado_id'], ['pla_prestamo_empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pla_amortizacion_prestamo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_amortizacion_prestamo_id'), ['id'], unique=False)

    op.create_table('pla_boleta_pago_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boleta_pago_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['boleta_pago_id'], ['pla_boleta_pago.id'], ),
    sa.ForeignKeyConstraint(['concepto_id'], ['pla_concepto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pla_boleta_pago_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pla_boleta_pago_detalle_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pla_boleta_pago_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_boleta_pago_detalle_id'))

    op.drop_table('pla_boleta_pago_detalle')
    with op.batch_alter_table('pla_amortizacion_prestamo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_amortizacion_prestamo_id'))

    op.drop_table('pla_amortizacion_prestamo')
    with op.batch_alter_table('org_responsabilidad_puesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_responsabilidad_puesto_id'))

    op.drop_table('org_responsabilidad_puesto')
    with op.batch_alter_table('org_requisito_idioma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_requisito_idioma_id'))

    op.drop_table('org_requisito_idioma')
    with op.batch_alter_table('org_requisito_habilidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_requisito_habilidad_id'))

    op.drop_table('org_requisito_habilidad')
    with op.batch_alter_table('org_requisito_academico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_requisito_academico_id'))

    op.drop_table('org_requisito_academico')
    with op.batch_alter_table('org_asignacion_puesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_asignacion_puesto_id'))

    op.drop_table('org_asignacion_puesto')
    with op.batch_alter_table('seg_usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seg_usuario_id'))

    op.drop_table('seg_usuario')
    with op.batch_alter_table('rh_liquidacion_empleado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rh_liquidacion_empleado_id'))

    op.drop_table('rh_liquidacion_empleado')
    with op.batch_alter_table('pla_registro_comision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_registro_comision_id'))

    op.drop_table('pla_registro_comision')
    with op.batch_alter_table('pla_prestamo_empleado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_prestamo_empleado_id'))

    op.drop_table('pla_prestamo_empleado')
    with op.batch_alter_table('pla_novedad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_novedad_id'))

    op.drop_table('pla_novedad')
    with op.batch_alter_table('pla_boleta_pago', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_boleta_pago_id'))

    op.drop_table('pla_boleta_pago')
    with op.batch_alter_table('pla_beneficio_recurrente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_beneficio_recurrente_id'))

    op.drop_table('pla_beneficio_recurrente')
    with op.batch_alter_table('org_puesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_puesto_id'))

    op.drop_table('org_puesto')
    with op.batch_alter_table('experiencias_laborales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiencias_laborales_id'))

    op.drop_table('experiencias_laborales')
    with op.batch_alter_table('estudios_academicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estudios_academicos_id'))

    op.drop_table('estudios_academicos')
    with op.batch_alter_table('dependientes_economicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependientes_economicos_id'))

    op.drop_table('dependientes_economicos')
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_id'))

    op.drop_table('contratos')
    op.drop_table('seg_rol_permiso')
    with op.batch_alter_table('pla_periodo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_periodo_id'))

    op.drop_table('pla_periodo')
    with op.batch_alter_table('org_nivel_organizacional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_nivel_organizacional_id'))

    op.drop_table('org_nivel_organizacional')
    with op.batch_alter_table('org_estructura_organizativa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_estructura_organizativa_id'))

    op.drop_table('org_estructura_organizativa')
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empleados_nit'))
        batch_op.drop_index(batch_op.f('ix_empleados_id'))
        batch_op.drop_index(batch_op.f('ix_empleados_email_institucional'))
        batch_op.drop_index(batch_op.f('ix_empleados_dui'))

    op.drop_table('empleados')
    with op.batch_alter_table('seg_rol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seg_rol_id'))

    op.drop_table('seg_rol')
    with op.batch_alter_table('seg_permiso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seg_permiso_id'))

    op.drop_table('seg_permiso')
    with op.batch_alter_table('rh_catalogo_idioma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rh_catalogo_idioma_id'))

    op.drop_table('rh_catalogo_idioma')
    with op.batch_alter_table('rh_catalogo_habilidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rh_catalogo_habilidad_id'))

    op.drop_table('rh_catalogo_habilidad')
    with op.batch_alter_table('pla_tramo_renta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_tramo_renta_id'))

    op.drop_table('pla_tramo_renta')
    with op.batch_alter_table('pla_parametro_global', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_parametro_global_id'))

    op.drop_table('pla_parametro_global')
    with op.batch_alter_table('pla_concepto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pla_concepto_id'))

    op.drop_table('pla_concepto')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_nit'))
        batch_op.drop_index(batch_op.f('ix_empresas_id'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
