"""Add fields to PrestamoEmpleado

Revision ID: 7a2bd8738a1a
Revises: 58bd5856b181
Create Date: 2026-08-09 10:27:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2bd8738a1a'
down_revision: Union[str, None] = '58bd5856b181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pla_prestamo_empleado', sa.Column('entidad', sa.String(), nullable=True))
    op.add_column('pla_prestamo_empleado', sa.Column('fecha_inicio', sa.Date(), nullable=True))
    op.add_column('pla_prestamo_empleado', sa.Column('fecha_fin', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pla_prestamo_empleado', 'fecha_fin')
    op.drop_column('pla_prestamo_empleado', 'fecha_inicio')
    op.drop_column('pla_prestamo_empleado', 'entidad')
    # ### end Alembic commands ###
