// Catálogo oficial de la Reestructuración Municipal de El Salvador (Ley Especial N° 762)
// Contiene 14 Departamentos, 262 Distritos tradicionales y el mapeo a los 44 Nuevos Municipios.

export const DEPARTAMENTOS_SV = {
  "Ahuachapán": {
    "Ahuachapán": "Ahuachapán Centro",
    "Apaneca": "Ahuachapán Centro",
    "Atiquizaya": "Ahuachapán Norte",
    "Concepción de Ataco": "Ahuachapán Centro",
    "El Refugio": "Ahuachapán Norte",
    "Guaymango": "Ahuachapán Sur",
    "Jujutla": "Ahuachapán Sur",
    "San Francisco Menéndez": "Ahuachapán Sur",
    "San Lorenzo": "Ahuachapán Norte",
    "San Pedro Puxtla": "Ahuachapán Sur",
    "Tacuba": "Ahuachapán Centro",
    "Turín": "Ahuachapán Norte"
  },
  "Cabañas": {
    "Cinquera": "Cabañas Oeste",
    "Dolores": "Cabañas Este",
    "Guacotecti": "Cabañas Este",
    "Ilobasco": "Cabañas Oeste",
    "Jutiapa": "Cabañas Oeste",
    "San Isidro": "Cabañas Este",
    "Sensuntepeque": "Cabañas Este",
    "Tejutepeque": "Cabañas Oeste",
    "Victoria": "Cabañas Este"
  },
  "Chalatenango": {
    "Agua Caliente": "Chalatenango Centro",
    "Arcataao": "Chalatenango Sur",
    "Azacualpa": "Chalatenango Sur",
    "Cancasque": "Chalatenango Sur",
    "Chalatenango": "Chalatenango Sur",
    "Citalá": "Chalatenango Norte",
    "Comalapa": "Chalatenango Sur",
    "Concepción Quezaltepeque": "Chalatenango Sur",
    "Dulce Nombre de María": "Chalatenango Centro",
    "El Carrizal": "Chalatenango Sur",
    "El Paraíso": "Chalatenango Centro",
    "La Laguna": "Chalatenango Centro",
    "La Palma": "Chalatenango Norte",
    "La Reina": "Chalatenango Centro",
    "Las Vueltas": "Chalatenango Sur",
    "Nombre de Jesús": "Chalatenango Sur",
    "Nueva Concepción": "Chalatenango Centro",
    "Nueva Trinidad": "Chalatenango Sur",
    "Ojos de Agua": "Chalatenango Sur",
    "Potonico": "Chalatenango Sur",
    "San Antonio de la Cruz": "Chalatenango Sur",
    "San Antonio Los Ranchos": "Chalatenango Sur",
    "San Fernando": "Chalatenango Centro",
    "San Francisco Lempa": "Chalatenango Sur",
    "San Francisco Morazán": "Chalatenango Centro",
    "San Ignacio": "Chalatenango Norte",
    "San Isidro Labrador": "Chalatenango Sur",
    "San José Cancasque": "Chalatenango Sur",
    "San José Las Flores": "Chalatenango Sur",
    "San Luis del Carmen": "Chalatenango Sur",
    "San Miguel de Mercedes": "Chalatenango Sur",
    "San Rafael": "Chalatenango Centro",
    "Santa Rita": "Chalatenango Centro"
  },
  "Cuscatlán": {
    "Candelaria": "Cuscatlán Sur",
    "Cojutepeque": "Cuscatlán Sur",
    "El Carmen": "Cuscatlán Sur",
    "El Rosario": "Cuscatlán Sur",
    "Monte San Juan": "Cuscatlán Sur",
    "Oratorio de Concepción": "Cuscatlán Norte",
    "San Bartolomé Perulapía": "Cuscatlán Norte",
    "San Cristóbal": "Cuscatlán Sur",
    "San José Guayabal": "Cuscatlán Norte",
    "San Pedro Perulapán": "Cuscatlán Norte",
    "San Rafael Cedros": "Cuscatlán Sur",
    "San Ramón": "Cuscatlán Sur",
    "Santa Cruz Analquito": "Cuscatlán Sur",
    "Santa Cruz Michapa": "Cuscatlán Sur",
    "Suchitoto": "Cuscatlán Norte",
    "Tenancingo": "Cuscatlán Sur"
  },
  "La Libertad": {
    "Antiguo Cuscatlán": "La Libertad Este",
    "Chiltiupán": "La Libertad Costa",
    "Ciudad Arce": "La Libertad Centro",
    "Colón": "La Libertad Oeste",
    "Comasagua": "La Libertad Sur",
    "Huizúcar": "La Libertad Este",
    "Jayaque": "La Libertad Oeste",
    "Jicalapa": "La Libertad Costa",
    "La Libertad": "La Libertad Costa",
    "Nuevo Cuscatlán": "La Libertad Este",
    "Quezaltepeque": "La Libertad Norte",
    "Sacacoyo": "La Libertad Oeste",
    "San José Villanueva": "La Libertad Este",
    "San Juan Opico": "La Libertad Centro",
    "San Matías": "La Libertad Norte",
    "San Pablo Tacachico": "La Libertad Norte",
    "Santa Tecla": "La Libertad Sur",
    "Talnique": "La Libertad Oeste",
    "Tamanique": "La Libertad Costa",
    "Teotepeque": "La Libertad Costa",
    "Tepecoyo": "La Libertad Oeste",
    "Zaragoza": "La Libertad Este"
  },
  "La Paz": {
    "Cuyultitán": "La Paz Oeste",
    "El Rosario": "La Paz Centro",
    "Jerusalén": "La Paz Centro",
    "Mercedes La Ceiba": "La Paz Centro",
    "Olocuilta": "La Paz Oeste",
    "Paraíso de Osorio": "La Paz Centro",
    "San Antonio Masahuat": "La Paz Centro",
    "San Emigdio": "La Paz Centro",
    "San Francisco Chinameca": "La Paz Oeste",
    "San Juan Nonualco": "La Paz Este",
    "San Juan Talpa": "La Paz Oeste",
    "San Juan Tepezontes": "La Paz Centro",
    "San Luis La Herradura": "La Paz Centro",
    "San Luis Talpa": "La Paz Oeste",
    "San Miguel Tepezontes": "La Paz Centro",
    "San Pedro Masahuat": "La Paz Oeste",
    "San Pedro Nonualco": "La Paz Centro",
    "San Rafael Obrajuelo": "La Paz Este",
    "Santa María Ostuma": "La Paz Centro",
    "Santiago Nonualco": "La Paz Centro",
    "Tapalhuaca": "La Paz Oeste",
    "Zacatecoluca": "La Paz Este"
  },
  "La Unión": {
    "Anamorós": "La Unión Norte",
    "Bolívar": "La Unión Norte",
    "Concepción de Oriente": "La Unión Norte",
    "Conchagua": "La Unión Sur",
    "El Carmen": "La Unión Sur",
    "El Sauce": "La Unión Norte",
    "Intipucá": "La Unión Sur",
    "La Unión": "La Unión Sur",
    "Lislique": "La Unión Norte",
    "Meanguera del Golfo": "La Unión Sur",
    "Nueva Esparta": "La Unión Norte",
    "Pasaquina": "La Unión Norte",
    "Polorós": "La Unión Norte",
    "San Alejo": "La Unión Sur",
    "San José": "La Unión Norte",
    "Santa Rosa de Lima": "La Unión Norte",
    "Yayantique": "La Unión Sur",
    "Yucuaiquín": "La Unión Sur"
  },
  "Morazán": {
    "Arambala": "Morazán Norte",
    "Cacaopera": "Morazán Norte",
    "Chilanga": "Morazán Sur",
    "Corinto": "Morazán Norte",
    "Delicias de Concepción": "Morazán Sur",
    "El Divisadero": "Morazán Sur",
    "El Rosario": "Morazán Norte",
    "Gualococti": "Morazán Sur",
    "Guatajiagua": "Morazán Sur",
    "Joateca": "Morazán Norte",
    "Jocoaitique": "Morazán Norte",
    "Jocoro": "Morazán Sur",
    "Lolotiquillo": "Morazán Sur",
    "Meanguera": "Morazán Norte",
    "Osicala": "Morazán Sur",
    "Perquín": "Morazán Norte",
    "San Carlos": "Morazán Sur",
    "San Fernando": "Morazán Norte",
    "San Francisco Gotera": "Morazán Sur",
    "San Isidro": "Morazán Norte",
    "San Simón": "Morazán Sur",
    "Sensembra": "Morazán Sur",
    "Sociedad": "Morazán Sur",
    "Torola": "Morazán Norte",
    "Yamabal": "Morazán Sur",
    "Yoloaiquín": "Morazán Sur"
  },
  "San Miguel": {
    "Carolina": "San Miguel Norte",
    "Chapeltique": "San Miguel Norte",
    "Chinameca": "San Miguel Oeste",
    "Chirilagua": "San Miguel Centro",
    "Ciudad Barrios": "San Miguel Norte",
    "Comacarán": "San Miguel Centro",
    "El Tránsito": "San Miguel Oeste",
    "Lolotique": "San Miguel Oeste",
    "Moncagua": "San Miguel Centro",
    "Nueva Guadalupe": "San Miguel Oeste",
    "Nuevo Edén de San Juan": "San Miguel Norte",
    "Quelepa": "San Miguel Centro",
    "San Antonio del Mosco": "San Miguel Norte",
    "San Gerardo": "San Miguel Norte",
    "San Jorge": "San Miguel Oeste",
    "San Luis de la Reina": "San Miguel Norte",
    "San Miguel": "San Miguel Centro",
    "San Rafael Oriente": "San Miguel Oeste",
    "Sesori": "San Miguel Norte",
    "Uluazapa": "San Miguel Centro"
  },
  "San Salvador": {
    "Aguilares": "San Salvador Norte",
    "Apopa": "San Salvador Oeste",
    "Ayutuxtepeque": "San Salvador Centro",
    "Ciudad Delgado": "San Salvador Centro",
    "Cuscatancingo": "San Salvador Centro",
    "El Paisnal": "San Salvador Norte",
    "Guazapa": "San Salvador Norte",
    "Ilopango": "San Salvador Este",
    "Mejicanos": "San Salvador Centro",
    "Nejapa": "San Salvador Oeste",
    "Panchimalco": "San Salvador Sur",
    "Rosario de Mora": "San Salvador Sur",
    "San Marcos": "San Salvador Sur",
    "San Martín": "San Salvador Este",
    "San Salvador": "San Salvador Centro",
    "Santiago Texacuangos": "San Salvador Sur",
    "Santo Tomás": "San Salvador Sur",
    "Soyapango": "San Salvador Este",
    "Tonacatepeque": "San Salvador Este"
  },
  "San Vicente": {
    "Apastepeque": "San Vicente Norte",
    "Guadalupe": "San Vicente Sur",
    "San Cayetano Istepeque": "San Vicente Sur",
    "San Esteban Catarina": "San Vicente Norte",
    "San Ildefonso": "San Vicente Norte",
    "San Lorenzo": "San Vicente Norte",
    "San Sebastián": "San Vicente Norte",
    "San Vicente": "San Vicente Sur",
    "Santa Clara": "San Vicente Norte",
    "Santo Domingo": "San Vicente Norte",
    "Tecoluca": "San Vicente Sur",
    "Tepetitán": "San Vicente Sur",
    "Verapaz": "San Vicente Sur"
  },
  "Santa Ana": {
    "Candelaria de la Frontera": "Santa Ana Oeste",
    "Chalchuapa": "Santa Ana Oeste",
    "Coatepeque": "Santa Ana Este",
    "El Congo": "Santa Ana Este",
    "El Porvenir": "Santa Ana Oeste",
    "Masahuat": "Santa Ana Norte",
    "Metapán": "Santa Ana Norte",
    "San Antonio Pajonal": "Santa Ana Oeste",
    "San Sebastián Salitrillo": "Santa Ana Oeste",
    "Santa Ana": "Santa Ana Centro",
    "Santa Rosa Guachipilín": "Santa Ana Norte",
    "Santiago de la Frontera": "Santa Ana Oeste",
    "Texistepeque": "Santa Ana Norte"
  },
  "Sonsonate": {
    "Acajutla": "Sonsonate Oeste",
    "Armenia": "Sonsonate Este",
    "Caluco": "Sonsonate Este",
    "Cuisnahuat": "Sonsonate Este",
    "Izalco": "Sonsonate Este",
    "Juayúa": "Sonsonate Norte",
    "Nahuizalco": "Sonsonate Norte",
    "Nahulingo": "Sonsonate Centro",
    "Salcoatitán": "Sonsonate Norte",
    "San Antonio del Monte": "Sonsonate Centro",
    "San Julián": "Sonsonate Este",
    "Santa Catarina Masahuat": "Sonsonate Norte",
    "Santa Isabel Ishuatán": "Sonsonate Este",
    "Santo Domingo de Guzmán": "Sonsonate Centro",
    "Sonsonate": "Sonsonate Centro",
    "Sonzacate": "Sonsonate Centro"
  },
  "Usulután": {
    "Alegría": "Usulután Norte",
    "Berlín": "Usulután Norte",
    "California": "Usulután Este",
    "Concepción Batres": "Usulután Este",
    "El Triunfo": "Usulután Norte",
    "Ereguayquín": "Usulután Este",
    "Estanzuelas": "Usulután Norte",
    "Jiquilisco": "Usulután Oeste",
    "Jucuapa": "Usulután Norte",
    "Jucuarán": "Usulután Este",
    "Mercedes Umaña": "Usulután Norte",
    "Nueva Granada": "Usulután Norte",
    "Ozatlán": "Usulután Este",
    "Puerto El Triunfo": "Usulután Oeste",
    "San Agustín": "Usulután Este",
    "San Buenaventura": "Usulután Norte",
    "San Dionisio": "Usulután Este",
    "San Francisco Javier": "Usulután Oeste",
    "Santa Elena": "Usulután Este",
    "Santa María": "Usulután Este",
    "Santiago de María": "Usulután Norte",
    "Tecapán": "Usulután Este",
    "Usulután": "Usulután Este"
  }
};

export const LISTA_DEPARTAMENTOS = Object.keys(DEPARTAMENTOS_SV);

export function obtenerDistritosPorDepartamento(depto) {
  if (!depto || !DEPARTAMENTOS_SV[depto]) return [];
  return Object.keys(DEPARTAMENTOS_SV[depto]).sort();
}

export function obtenerMunicipioOficial(depto, distrito) {
  if (!depto || !distrito || !DEPARTAMENTOS_SV[depto]) return '';
  return DEPARTAMENTOS_SV[depto][distrito] || '';
}
